name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Checkout private tools        
      uses: actions/checkout@v3
      with:
        repository: uc-vision/lint-settings
        path: lint-settings
    - name: Lint with flake8
      run: |
        python -m pip install toml flake8
        flake8 . --rcfile=lint-settings/pylintrc
